name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: GoReleaser Action
        # You may pin to the exact commit or the version.
        # uses: goreleaser/goreleaser-action@ac067437f516133269923265894e77920c3dce18
        uses: goreleaser/goreleaser-action@v2.6.1
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
